
services:
    crud_webapi:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        container_name: to_do_web_api
        depends_on:
            - db
        environment:
            ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
            Jwt__Key: ${JWT_KEY}
            Jwt__Issuer: ${JWT_ISSUER}
            Jwt__Audience: ${JWT_AUDIENCE}
    db:
        image: postgres:17
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
        volumes:
            - db_data:/var/lib/postgresql/data
        container_name: db_postgresql_container
        
volumes:
    db_data:    